services:
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
      target: runner
    env_file:
      - ./apps/frontend/.env.production
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - INTERNAL_API_URL=http://backend:8000

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
      target: runner
    working_dir: /app
    env_file:
      - ./apps/backend/.env.production
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./data/prod.db
    volumes:
      - ./apps/backend/data:/app/data
