services:
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
      target: dev
    volumes:
      - ./apps/frontend:/app/apps/frontend:cached
      - ./packages:/app/packages:cached
    working_dir: /app
    command: sh -c "pnpm install && pnpm --filter frontend dev --turbo"
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - INTERNAL_API_URL=http://backend:8000
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - CORS_ORIGINS=${CORS_ORIGINS}


  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
      target: dev
    # Mount code for uvicorn --reload
    # If your main.py is under apps/backend/app/, use that path:
    volumes:
      - type: tmpfs
        target: /app/data
      - ./apps/backend:/app:cached
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./data/dev.db
      - CLERK_JWKS_URL=${CLERK_JWKS_URL}
      - JWT_ISSUER=${JWT_ISSUER}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - APP_ENV="development"
